Change "collections" into "collections.abc" for Python 3.10 compatibility (#305)
* Change "collections" into "collections.abc" for Python 3.10 compatibility

For Python 3.10 compatibility, "from collections import Iterable" should be changed into "from collections.abc import Iterable".
See for example:
https://stackoverflow.com/questions/72032032/importerror-cannot-import-name-iterable-from-collections-in-python

* Fix "black" and "flake8" errors

* Fix indentation error E129 from "black" and "flake8"

Fix the following error:
cesium/time_series.py:235:13: E129 visually indented line with same indent as next logical line

* Update black to version 22.3.0

Update black version to 22.3.0 to solve the following error:
ImportError: cannot import name '_unicodefun' from 'click'
See: https://github.com/psf/black/issues/2964 
Or: https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click

* Reformat "cesium/time_series.py" with "black"

I have used "black --line-length=80" on the file "cesium/time_series.py".
The option "--line-length=80" is used to respect the flake8 line length specification given in the file "cesium/.flake8": "max-line-length = 80".

* Change flake8 max-line-length from 80 to 88

* Use "black" format on the file "cesium/time_series.py"